//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SR13-ImportParts.rc
//
#define IDS_SR13_IMPORTPARTS_ERR_ALREADYCOMPLETE 13000
#define IDS_SR13_IMPORTPARTS_ERR_HASHSETINCOMPLETE 13001
#define IDS_SR13_IMPORTPARTS_ERR_CANTOPENFILE 13002
#define IDS_SR13_IMPORTPARTS_IMPORTSTART 13003
#define IDS_SR13_IMPORTPARTS_PARTSKIPPEDALREADYCOMPLETE 13004
#define IDS_SR13_IMPORTPARTS_PARTIMPORTEDGOOD 13005
#define IDS_SR13_IMPORTPARTS_PARTIMPORTEDBAD 13006
#define IDS_SR13_IMPORTPARTS_PARTSKIPPEDDONTMATCH 13007
#define IDS_SR13_IMPORTPARTS_BADPARTSREHASH 13008
#define IDS_SR13_IMPORTPARTS_ERR_ALREADYINPROGRESS 13009
#define IDS_SR13_IMPORTPARTS_IMPORTFINISH 13010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
